title:            Alex Hagen
tagline:          xdsaf
description:      >
  Welcome to my portfolio. I am currently a Ph.D. seeking student
  at Purdue University in Nuclear Engineering.  This portfolio
  shows some designs, publications, and open source codes that I've
  created. Feel free to email me if you have any ideas, questions, or requests.
canonical: http://alexhagen.github.io

# Owner/author information
owner:
  name:           Alex Hagen
  avatar:         avatar.png
  bio:            >
    Welcome to my portfolio. I am currently a Ph.D. seeking student
    at Purdue University in Nuclear Engineering.  This portfolio
    shows some designs, publications, and open source codes that I've
    created. Feel free to email me if you have any ideas, questions, or requests.
  email:          alexhagen6@gmail.com
  github:         alexhagen
  location:       "Lafayette, IN"

tools:
  standards:      "MATLAB, Python, C++, QT, FORTRAN, PHP"
  software:       "COMSOL, Solidworks, git, Inkscape"

# Links to include in top navigation
# For external links add external: true
links:
  - title: Portfolio
    short_title: work
    url: /portfolio
    important: true
  - title: Chronicle
    short_title: blog
    url: /chronicle
    important: false
  - title: CV
    short_title: CV
    url: /cv
    important: true
  - title: Github
    short_title: GH
    icon: github_icon.svg
    url: https://github.com/alexhagen
    external: true
    important: true
  - title: Research Gate
    short_title: RG
    icon: researchgate_icon.svg
    url: https://www.researchgate.net/profile/Alexander_Hagen2
    external: true
    important: true
  - title: LinkedIn
    short_title: LI
    icon: linkedin_icon.svg
    url: https://www.linkedin.com/in/alexander-hagen-61593423/
    external: true
    important: false
  - title: GrabCad
    short_title: GC
    icon: grabcad_icon.svg
    url: https://grabcad.com/alex.hagen-1
    external: true
    important: false

timezone:    America/New_York
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
